// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class ChangeNumber extends ethereum.Event {
  get params(): ChangeNumber__Params {
    return new ChangeNumber__Params(this);
  }
}

export class ChangeNumber__Params {
  _event: ChangeNumber;

  constructor(event: ChangeNumber) {
    this._event = event;
  }

  get timestamp(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get oldValue(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get newValue(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get caller(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class Storage extends ethereum.SmartContract {
  static bind(address: Address): Storage {
    return new Storage("Storage", address);
  }

  retrieve(): BigInt {
    let result = super.call("retrieve", "retrieve():(uint256)", []);

    return result[0].toBigInt();
  }

  try_retrieve(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("retrieve", "retrieve():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class StoreCall extends ethereum.Call {
  get inputs(): StoreCall__Inputs {
    return new StoreCall__Inputs(this);
  }

  get outputs(): StoreCall__Outputs {
    return new StoreCall__Outputs(this);
  }
}

export class StoreCall__Inputs {
  _call: StoreCall;

  constructor(call: StoreCall) {
    this._call = call;
  }

  get num(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class StoreCall__Outputs {
  _call: StoreCall;

  constructor(call: StoreCall) {
    this._call = call;
  }
}
